<a href="https://colab.research.google.com/github/InnaK342/nn2022/blob/main/Lab1/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1 Ківачук Інна 

## Завдання 1 Numpy
створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Властивість shape та метод  reshape. Операції над масивами. Використати arange, random.


In [23]:
import numpy as np

scalar=np.random.randint(0, 10)
vector_1=np.arange(0, 3, 1)
vector_2=[4, 5, 6]
matrix_1=np.array([[1,2,3],[4,5,6]])
matrix_2=np.random.randint(10, size=(2, 3))

print(matrix_1.shape)

print(matrix_1*matrix_2)
print(matrix_1+matrix_2)

print(vector_1+vector_2)
print(vector_1*scalar)

vector_3 = np.array(range(10), int)
matrix_3 = vector_3.reshape(5,2)
print(matrix_3)

(2, 3)
[[ 9 14 15]
 [32 30 12]]
[[10  9  8]
 [12 11  8]]
[4 6 8]
[0 4 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Завдання 2 Pandas
створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..)

In [59]:
import pandas as pd
import numpy as np

df_1 = pd.DataFrame() 
print('df_1\n',df_1)

data = {'color' : ['blue', 'green', 'yellow'],
        'object' : ['ball', 'pen', 'pencil'],
        'price' : [1.2, 1.0, 0.6]}
df_2 = pd.DataFrame(data)
print('df_2\n',df_2)

matrix = np.random.randint(10, size=(3, 5))
df_3 = pd.DataFrame(matrix)

print('df_3\n',df_3)

df_4 = pd.DataFrame(data, columns=['object', 'price'])
print('df_4\n',df_4)

# операції
print(df_2.head(2))
print(df_2.describe())
print(df_3.describe(include='all')) 

print(df_2.iloc[0]) 
print(df_2.iloc[[0, 2]])


print(df_2.loc[0]['color']) 
print(df_2.loc[df_2['price']>1]) 
print(df_3.loc[df_3[0]%2==0]) 

df_2_price = df_2.groupby(by=['price']).min()
print(df_2_price)

print(df_2.sort_values(by='price', ascending=False))

print(df_2['price'].isnull().head(3))

df_1
 Empty DataFrame
Columns: []
Index: []
df_2
     color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
df_3
    0  1  2  3  4
0  2  0  3  8  9
1  3  8  1  4  7
2  6  8  0  9  6
df_4
    object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
   color object  price
0   blue   ball    1.2
1  green    pen    1.0
          price
count  3.000000
mean   0.933333
std    0.305505
min    0.600000
25%    0.800000
50%    1.000000
75%    1.100000
max    1.200000
              0         1         2         3         4
count  3.000000  3.000000  3.000000  3.000000  3.000000
mean   3.666667  5.333333  1.333333  7.000000  7.333333
std    2.081666  4.618802  1.527525  2.645751  1.527525
min    2.000000  0.000000  0.000000  4.000000  6.000000
25%    2.500000  4.000000  0.500000  6.000000  6.500000
50%    3.000000  8.000000  1.000000  8.000000  7.000000
75%    4.500000  8.000000  2.000000  8.500000  8.000000
max    6.000000  8.000000  3.000000  9.00

## Завдання 3 Matplotlib
створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)

## Завдання 4 Завантаження наборів даних з інтернету

## Завдання 5 Параметри доступу до графічних процесорів