<a href="https://colab.research.google.com/github/InnaK342/nn2022/blob/main/Lab2/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 2 Ківачук Інна


##Різні способи створення тензорів


In [15]:
import tensorflow as tf
print(tf.__version__) 

#tf.constant()
scalar = tf.constant(5)
print(scalar)

vector = tf.constant([5, 5])
print(vector)

matrix = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
print(matrix)

float_matrix = tf.constant([[10.1, 7.2],
                              [4.5, 2.],
                              [8., 9.]], dtype=tf.float16)
print(float_matrix)

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print(tensor)

#tf.Variable()
tensor_2 = tf.Variable([1, 2, 3])
print(tensor_2)
tensor_2[0].assign(100)
print(tensor_2)

#random tensors
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])

print(tf.random.shuffle(not_shuffled))

print(tf.random.shuffle(not_shuffled, seed=42))

random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3, 2))
print(random_tensor)

#other ways
print(tf.ones(shape=(5, 5)))
print(tf.zeros(shape=(3, 4)))

2.8.0
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([5 5], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10.1  7.2]
 [ 4.5  2. ]
 [ 8.   9. ]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100,   2,   3], dtype=int32)>
tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


##Створити набір даних із заданим розподілом, визначити його властивості (shape, rank, size, axis)


In [17]:
import tensorflow as tf

tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
print("Datatype", tensor.dtype)
print("Rank:", tensor.ndim)
print("Shape of tensor:", tensor.shape)
print("Axis 0 of tensor:", tensor.shape[0])
print("Last axis of tensor:", tensor.shape[-1])
print("Count of elements:", tf.size(tensor).numpy())

Datatype <dtype: 'int32'>
Rank: 2
Shape of tensor: (3, 2)
Axis 0 of tensor: 3
Last axis of tensor: 2
Count of elements: 6


##Основні математичні операції над тензорами

In [40]:
import tensorflow as tf
import numpy as np

tensor_1 = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
tensor_2 = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print(tensor_1 + 20)
print(tf.multiply(tensor_1,20))
print(tf.reshape(tensor_1, shape=(2, 3)))
print(tf.transpose(tensor_1))
print(tf.matmul(tensor_1, tensor_2))
print(tf.tensordot(tensor_1, tensor_2, axes=1))

#Зміна типу
A = tf.constant([-3.5, -7.9])
A = tf.cast(A, dtype=tf.float16)
print(A)
print(tf.abs(A))
print(tf.square(A))
print(tf.sqrt(tf.abs(A)))


B = tf.constant(np.random.randint(low=0, high=50, size=10))
print(B)
print(tf.reduce_min(B))
print(tf.reduce_max(B))
print(tf.reduce_mean(B))
print(tf.reduce_sum(B))

print(tf.argmax(B))
print(tf.argmin(B))

C = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 1, 1, 50))
C_squeezed = tf.squeeze(C)
print(C_squeezed.shape)
print(C_squeezed.ndim)

D = tf.Variable(np.arange(0, 3))
D.assign([0, 1, 100])
print(D)
D.assign_add([10, 10, 10])
print(D)

tf.Tensor(
[[21 22]
 [23 24]
 [25 26]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 20  40]
 [ 60  80]
 [100 120]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 9 12 15]
 [19 26 33]
 [29 40 51]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9 12 15]
 [19 26 33]
 [29 40 51]], shape=(3, 3), dtype=int32)
tf.Tensor([-3.5 -7.9], shape=(2,), dtype=float16)
tf.Tensor([3.5 7.9], shape=(2,), dtype=float16)
tf.Tensor([12.25 62.38], shape=(2,), dtype=float16)
tf.Tensor([1.871 2.81 ], shape=(2,), dtype=float16)
tf.Tensor([29  0  9  3 34 16 14 49 39  6], shape=(10,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(49, shape=(), dtype=int64)
tf.Tensor(19, shape=(), dtype=int64)
tf.Tensor(199, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
(50,)
1
<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([0, 1, 2])>
<tf.Variable 'Varia

##Провести CRUD операції над даними, інтеграцію з np.array

In [44]:
tensor = tf.constant(np.array([1, 2, 3]))
print(np.array(tensor), type(np.array(tensor),))
print(tensor.numpy(), type(tensor.numpy()))



[1 2 3] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'>
